# Generated by Django 5.2.4 on 2025-07-21 19:09

import customers.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='approved_limit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='current_debt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='monthly_salary',
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default=customers.models.generate_customer_id, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
