# Generated by Django 5.2.4 on 2025-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_approved_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='approved_limit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='monthly_income',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
